<?php
include "config.php";
extract($_POST);
extract($_GET);

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset ="UTF-8">
	<title>Hakkımızda</title>
	<link rel="stylesheet" href="stil.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>
<body>
		<?php
	include "navbar.php";
	?>
	

	<section class="sectionhakkimizda">
		<div class="container mb-5">
			<div class="w-100">
			
			<img src=".\resimler\hakkimizda-resim.jpg" class="hakkimizdaResim float-start me-3 ">
			<h5 class="text-center">Hakkımızda</h5>
			<p class="text-left">Bizi doğuran annelerimize minettarız....Bugün anneler günü bütün annelerimizin anneler günün kutluyorum.. Onların hakkını hiç bir zaman hiç bir şekilde ödeyemeyiz...
				Ama bir yandan da isyanndayız o kadar kadın , anne bir gülüşe kanan  o erkekler cani bir şekilde her gün yüzlerce kadını ödürüyorlar ...bu anneler günü onların Anneler gününü minnet ve saygıyla ( anıp) kutluyoruz...Cenet annelerimizin ayağının altındadır onları koruyalım , sahip çıkalam kıymetini bilelim
				kara toprak altına girice mi sahip çıkacağız , kıymetini bileceğiz ? çoğumuzun yaptığı gibi ama yok  bu yazıyı okuyorsak eğer buna son verelim ... ya düşünün bir kadın sizi karşılıksız sevip , kolluyor işte o sadece annedir...
				Annemiz bizi 9 ay boyunca altına girice mi sahip çıkacağız , kıymetini bileceğiz ? çoğumuzun yaptığı gibi ama yok  bu yazıyı okuyorsak eğer buna son verelim ... ya düşünün bir kadın sizi karşılıksız sevip , kolluyor işte o sadece annedir...
				Annemiz bizi 9 ay boyunca ağrı ile taşıyor...
				ama biz doğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir altına girice mi sahip çıkacağız , kıymetini bileceğiz ? çoğumuzun yaptığı gibi ama yok  bu yazıyı okuyorsak eğer buna son verelim ... ya düşünün bir kadın sizi karşılıksız sevip , kolluyor işte o sadece annedir...
				Annemiz bizi 9 ay boyunca ağrı ile taşıyor...
				ama biz doğunca ğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir ağrı ile taşıyor...
				ama biz doğunca bu acılara değdibu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir ağrı ile taşıyor...
				ama biz doğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedeniğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir ağrı ile taşıyor...
				ama biz doğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedeniğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir ağrı ile taşıyor...
				ama biz doğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedeniğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir ağrı ile taşıyor...
				ama biz doğunca bu acılara değdiğini söylüyor...
				annelerimize çoğumuzun  ( sen yada ben yada biz yada siz yada onlar yada o demiyorum genelimiz diyorum.........)yaptığı gibi annemize "oflayıp pufluyoruz" yani yardım etsek yada bir iin ucundan tutsak elimize  yapımayacak ya herhalde onlar bizi doğduktan  , - ölene kadar yanımızdalar iyiide yanımızdalar....
				herkes mutlaka kendisini güzel buluyordur işte nedenine bugün  bir açıklık getireyim nedeni? annelerimizin hamil***n aynaya çok bakıp bizimde annemize çekmemizdir..=)...
				onları çok seviyoruz sakın annelirimiz bizde sizi çok seviyoruz demesinler demenize gerek yok çünkü iz biliyoruz sizin sevdiğinizi biz çoktan büyüdük ama sizin gözünüzde 3 yaşındaki çocuğuz  halen ben bu yazıyı sadece kendi annem için yazmadım sadece anneler içinde yazmadım ben bu yazıyı tüm kadınlara yazdım ( e yani bizde sizin evlatlarınız sayılırız değil mi ?) ve az daha unutuyordum bugün anneler günü<
			</p>
			</div>
			<div class="sosyal float-end">
				<ul>
				<li class="footerli mb-2">Başkent Sözlük Sosyal Medya Hesapları</li>
				<li class="sosyalli me-3"><a href="https://www.baskent.edu.tr/tr/"><img src=".\resimler\baskent-logo.png" width="50" height="50"></a></li>
				<li class="sosyalli me-3"><a href="https://twitter.com/baskentunv"><img src=".\resimler\twitter.png" width="60" height="40"></a></li>
				<li class="sosyalli me-3"><a href="https://www.youtube.com/@Baskentunv"><img src=".\resimler\youtube.png"  width="55" height="40"></a></li>
				<li class="sosyalli me-3"><a href="https://www.instagram.com/baskentunv/"><img src=".\resimler\instagram.png"  width="40" height="40"></a></li>
				<li class="sosyalli me-3"><a href="https://www.facebook.com/BaskentUniv/?locale=tr_TR"><img src=".\resimler\Facebook.png"  width="40" height="40"></a></li>
				<li class="sosyalli me-3"><a href="https://tr.linkedin.com/school/baskentuniversitesi/"><img src=".\resimler\linkedin.png"  width="40" height="40"></a></li>
			
				</ul>
			</div>
			<div class="w-100">
				<ul>
					<li class="saklama">a</li>
					<li class="saklama">b</li>
					<li class="saklama">c</li>
				</ul>
			</div>
		</div>
	</section>
	
	<?php
	include "footer.php";
	?>
</body>
</html>